- name: mongodb setup
  hosts: mongodb
  become: true
  vars:
    mongodb_version: "4.0"
  tasks:
    - name: copy the repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present


    - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'


    
    - name: re-start mongodb service
      ansible.builtin.service:
        name: mongod
        enabled: true
        state: started